server:
  port: 8081
 
spring:
  data:
    mongodb:
      host: 10.1.243.242
      port: 27017
      database: CustomObjects
---
  
spring: 
  profiles: dev
  data: 
    mongodb: 
      host: 172.17.0.2
      port: 27017 
      database: CustomObjects


---



  