---

server:
  port: 8081
 
spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: CustomObjects
---
  
spring: 
  profiles: dev
  data: 
    mongodb: 
      host: 192.168.1.210
      port: 27017 
      database: CustomObjects


---



  